meta_product_name: "Whatch"
meta_title: "Whatch - Your movie butler"
meta_description: "Don't know what to watch next? Whatch is an app that helps you decide what movie to watch easily. Take out the guesswork of choosing your next movie to watch. Let Whatch do the heavy-lifting for you. Sit back and Whatch!"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
