class CreateListOfServicesUsaJob < ApplicationJob
  queue_as :default

  def perform(*args)
    # repeat this for all services we need
    Service.create(company: "Apple iTunes", country: "USA")
    Service.create(company: "Google Play Movies", country: "USA")
    Service.create(company: "Vudu", country: "USA")
    Service.create(company: "Netflix", country: "USA")
    Service.create(company: "Amazon Prime Video", country: "USA")
    Service.create(company: "Amazon Video", country: "USA")
    Service.create(company: "Mubi", country: "USA")
    Service.create(company: "Crackle", country: "USA")
    Service.create(company: "realeyz", country: "USA")
    Service.create(company: "Hulu", country: "USA")
    Service.create(company: "Fandor", country: "USA")
    Service.create(company: "HBO Now", country: "USA")
    Service.create(company: "HBO Go", country: "USA")
    Service.create(company: "Showtime", country: "USA")
    Service.create(company: "Now TV", country: "USA")
    Service.create(company: "Starz", country: "USA")
    Service.create(company: "Microsoft Store", country: "USA")
    Service.create(company: "Tubi TV", country: "USA")
    Service.create(company: "CBS", country: "USA")
    Service.create(company: "NBC", country: "USA")
    Service.create(company: "AMC", country: "USA")
    Service.create(company: "The CW", country: "USA")
    Service.create(company: "Acorn TV", country: "USA")
    Service.create(company: "Shudder", country: "USA")
    Service.create(company: "GuideDoc", country: "USA")
    Service.create(company: "FandangoNow", country: "USA")
    Service.create(company: "FXNow", country: "USA")
    Service.create(company: "Max Go", country: "USA")
    Service.create(company: "Sundance Now", country: "USA")
    Service.create(company: "ABC", country: "USA")
    Service.create(company: "Brit Box", country: "USA")
    Service.create(company: "History", country: "USA")
    Service.create(company: "A&E", country: "USA")
    Service.create(company: "Lifetime", country: "USA")
    Service.create(company: "Netflix Kids", country: "USA")
    Service.create(company: "Pantaflix", country: "USA")
    Service.create(company: "Screambox", country: "USA")
    Service.create(company: "Youtube Premium", country: "USA")
    Service.create(company: "Curiosity Stream", country: "USA")
    Service.create(company: "Kanopy", country: "USA")
    Service.create(company: "Youtube", country: "USA")
    Service.create(company: "Starz Play Amazon Channel", country: "USA")
    Service.create(company: "AcornTV Amazon Channel", country: "USA")
    Service.create(company: "BritBox Amazon Channel", country: "USA")
    Service.create(company: "CBS All Access Amazon Channel", country: "USA")
    Service.create(company: "Fandor Amazon Channel", country: "USA")
    Service.create(company: "HBO Now Amazon Channel", country: "USA")
    Service.create(company: "Mubi Amazon Channel", country: "USA")
    Service.create(company: "Screambox Amazon Channel", country: "USA")
    Service.create(company: "Showtime Amazon Channel", country: "USA")
    Service.create(company: "Shudder Amazon Channel", country: "USA")
    Service.create(company: "Sundance Amazon Channel", country: "USA")
    Service.create(company: "CS Seed", country: "USA")
    Service.create(company: "The Roku Channel", country: "USA")
    Service.create(company: "PBS", country: "USA")
    Service.create(company: "Freeform", country: "USA")
    Service.create(company: "Hoopla", country: "USA")
    Service.create(company: "Syfy", country: "USA")
    Service.create(company: "Eros Now", country: "USA")
    Service.create(company: "DC Universe", country: "USA")
    Service.create(company: "Youtube Free", country: "USA")
    Service.create(company: "IMDb TV", country: "USA")
    Service.create(company: "Popcornflix", country: "USA")
    Service.create(company: "Comedy Central", country: "USA")
    Service.create(company: "Pantaya", country: "USA")
    Service.create(company: "Boomerang", country: "USA")
    Service.create(company: "UP Faith and Family", country: "USA")
    Service.create(company: "Urban Movie Channel", country: "USA")
    Service.create(company: "Dove Channel", country: "USA")
    Service.create(company: "Yupp TV", country: "USA")
    Service.create(company: "fuboTV", country: "USA")
    Service.create(company: "Criterion Channel", country: "USA")
    Service.create(company: "Magnolia Selects", country: "USA")
    Service.create(company: "WWE Network", country: "USA")
    Service.create(company: "Nickhits Amazon Channel", country: "USA")
    Service.create(company: "Noggin Amazon Channel", country: "USA")
    Service.create(company: "MyOutdoorTV", country: "USA")
    Service.create(company: "Tribeca Shortlist", country: "USA")
    Service.create(company: "Hopster TV", country: "USA")
    Service.create(company: "History Vault", country: "USA")
    Service.create(company: "Funimation Now", country: "USA")
    Service.create(company: "Laugh Out Loud", country: "USA")
    Service.create(company: "Smithsonian Channel", country: "USA")
    Service.create(company: "Pure Flix", country: "USA")
    Service.create(company: "Redbox", country: "USA")
    Service.create(company: "Hallmark Movies", country: "USA")
    Service.create(company: "Sports Illustrated", country: "USA")
    Service.create(company: "Crunchyroll", country: "USA")
    Service.create(company: "Lifetime Movie Club", country: "USA")
    Service.create(company: "Boomerang Amazon Channel", country: "USA")
    Service.create(company: "Cinemax Amazon Channel", country: "USA")
    Service.create(company: "Hallmark Movies Amazon Channel", country: "USA")
    Service.create(company: "MZ Choice Amazon Channel", country: "USA")
    Service.create(company: "Pantaya Amazon Channel", country: "USA")
    Service.create(company: "PBS Kids Amazon Channel", country: "USA")
    Service.create(company: "PBS Masterpiece Amazon Channel", country: "USA")
    Service.create(company: "Viewster Amazon Channel", country: "USA")
    Service.create(company: "Sling TV", country: "USA")
    Service.create(company: "PLuto TV", country: "USA")
    Service.create(company: "Cartoon Network", country: "USA")
    Service.create(company: "Adult Swim", country: "USA")
    Service.create(company: "USA Network", country: "USA")
    Service.create(company: "Fox", country: "USA")
    Service.create(company: "Snag Films", country: "USA")
    Service.create(company: "FlixFling", country: "USA")
    Service.create(company: "VUDU Free", country: "USA")
    Service.create(company: "Disney Plus", country: "USA")
    Service.create(company: "Bet+ Amazon Channel", country: "USA")
    Service.create(company: "Rakuten Viki", country: "USA")
    Service.create(company: "Apple TV Plus", country: "USA")
    Service.create(company: "AMC on Demand", country: "USA")
    Service.create(company: "Darkmatter TV", country: "USA")
    Service.create(company: "DIRECTV", country: "USA")
    Service.create(company: "TCM", country: "USA")
    Service.create(company: "TNT", country: "USA")
    Service.create(company: "Bravo TV", country: "USA")
    Service.create(company: "Food Network", country: "USA")
    Service.create(company: "IndieFlix", country: "USA")
    Service.create(company: "Quibi", country: "USA")
    # we need one of this per movie
    # AvailableService.create(service_id: 'reference the relevant service', movie_id: 'reference correct movie with OUR id, not tmdb', url: 'link to the movie')

  end
end
